# Generated by Django 4.1.4 on 2022-12-27 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0002_alter_tag_options'),
        ('author', '0003_alter_author_options_author_post_permission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Title')),
                ('body', models.TextField(null=True, verbose_name='Body')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='author.author', verbose_name='Author')),
                ('tag', models.ManyToManyField(to='tag.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': "Post's",
                'ordering': ['-date_created'],
            },
        ),
    ]
