# Generated by Django 4.1.4 on 2022-12-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': "Author's"},
        ),
        migrations.AddField(
            model_name='author',
            name='post_permission',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Permissão para Post'),
        ),
        migrations.AddField(
            model_name='author',
            name='tag_permission',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Permissão para Tag'),
        ),
    ]
